// Generated by CoffeeScript 1.6.2
(function() {
  var Deploy, async, fs, jsdom, request;

  request = require('request');

  jsdom = require('jsdom');

  fs = require('fs');

  async = require('async');

  Deploy = (function() {
    function Deploy(username, password, server) {
      var _ref;

      this.username = username;
      this.password = password;
      this.server = server;
      if ((_ref = this.server) == null) {
        this.server = 'rally1.rallydev.com';
      }
    }

    Deploy.prototype.createNewPage = function(cpoid, name, content, tab, callback) {
      var dashboardOid, panelOid;

      dashboardOid = null;
      return panelOid = null;
    };

    async.waterfall([
      Deploy._login, 
      function(res, b, cb) {
        var mtab, options;

        mtab = tab || 'myhome';
        return options = {
          url: "https://" + this.server + "/slm/wt/edit/create.sp",
          method: 'POST',
          followAllRedirects: true,
          form: {
            name: name,
            type: 'DASHBOARD',
            timeboxFilter: 'none',
            pid: mtab,
            editorMode: 'create',
            cpoid: cpoid,
            version: 0
          }
        };
      }, request(options, cb), function(results, body, cb) {
        return jsdom.env(body, cb);
      }, function(window, cb) {
        var dashboardOid, oidElt, options, _ref;

        oidElt = window.document.getElementsByName('oid');
        dashboardOid = oidElt != null ? (_ref = oidElt[0]) != null ? _ref.value : void 0 : void 0;
        options = {
          url: "https://" + this.server + "/slm/panel/getCatalogPanels.sp?cpoid=" + cpoid + "&ignorePanelDefOids&gesture=getcatalogpaneldefs&_slug=/custom/" + dashboardOid,
          method: 'GET'
        };
        return request(options, cb);
      }, function(results, body, cb) {
        var options, p, panels, ptoid, _i, _len;

        panels = JSON.parse(body);
        for (_i = 0, _len = panels.length; _i < _len; _i++) {
          p = panels[_i];
          if (p.title === "Custom HTML") {
            ptoid = p.oid;
          }
        }
        options = {
          url: "https://" + this.server + "/slm/dashboard/addpanel.sp?cpoid=" + cpoid + "&_slug=/custom/" + dashboardOid,
          method: 'POST',
          followAllRedirects: true,
          form: {
            panelDefinitionOid: ptoid,
            col: 0,
            index: 0,
            dashboardName: "" + tab + dashboardOid,
            gestrure: 'addpanel'
          }
        };
        return request(options, cb);
      }, function(results, body, cb) {
        var options, panelOid;

        panelOid = JSON.parse(body).oid;
        options = {
          url: "https://" + this.server + "/slm/dashboard/changepanelsettings.sp?cpoid=" + cpoid + "&_slug=/custom/" + dashboardOid,
          method: 'POST',
          followAllRedirects: true,
          form: {
            oid: panelOid,
            dashboardName: "" + tab + dashboardOid,
            settings: JSON.stringify({
              title: name,
              content: content
            }),
            gestrure: 'changepanelsettings'
          }
        };
        return request(options, cb);
      }, function(results, body, cb) {
        var options;

        options = {
          url: "https://" + this.server + "/slm/dashboardSwitchLayout.sp?cpoid=" + cpoid + "&layout=SINGLE&dashboardName=" + tab + dashboardOid + "&_slug=/custom/" + dashboardOid,
          method: 'GET'
        };
        return request(options, cb);
      }, function(results, body, cb) {}
    ], function(err) {
      return callback(dashboardOid, panelOid);
    });

    Deploy.prototype.updatePage = function(doid, poid, cpoid, name, tab, content, callback) {
      return this._login(function(err, res, b) {
        var mtab, options;

        mtab = tab || 'myhome';
        options = {
          url: "https://" + this.server + "/slm/dashboard/changepanelsettings.sp?cpoid=" + cpoid + "&_slug=/custom/" + doid,
          method: 'POST',
          followAllRedirects: true,
          form: {
            oid: poid,
            dashboardName: "" + tab + doid,
            settings: JSON.stringify({
              title: name,
              content: content
            }),
            gestrure: 'changepanelsettings'
          }
        };
        return request(options, function(error, results, body) {
          return callback();
        });
      });
    };

    Deploy.prototype._login = function(callback) {
      var options;

      options = {
        url: "https://" + this.server + "/slm/platform/j_platform_security_check.op",
        method: 'POST',
        followAllRedirects: true,
        form: {
          j_username: this.username,
          j_password: this.password
        }
      };
      return request(options, function(err, res, body) {
        return callback(err, res, body);
      });
    };

    return Deploy;

  })();

  exports.Deploy = Deploy;

}).call(this);
